### PR TITLE
Add register now button on event card

### LINKED ISSUE #73: GOSA28 - Add register now button on event card
The button must push to the registration screen.

### PR DESCRIPTION
**Pull request by singhtaran1005**
GOSA28
ISSUE #73 

#### Describe the changes you've made
added register now button

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by VarunSAthreya — CHANGES_REQUESTED** [review]
Use `routeName`  for navigation

**Comment by singhtaran1005** [comment]
okay

**Comment by singhtaran1005** [comment]
changes done

**Review by VarunSAthreya — APPROVED** [review]
Congratulations on the successful merge!
The next set of issues would be out soon.

**Pull request merged**
