### PR TITLE
UI for committee member section

### LINKED ISSUE #6: GOSA5 - UI for Committee Members section
#### Description
GeeksforGeeks student chapter committee member details.

You can create cards for members or be creative and do something innovative.

### PR DESCRIPTION
**Pull request by singhtaran1005**
#### GOSA5
ISSUE #6 

#### Describe the changes you've made
I have made the UI for committee members , along with a constraints page . In the committee members list i have made black sections where members can fill their description  , photo , name , designation and their basic social media handles.
All members are in a list view.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Screenshots added
WhatsApp Image 2020-10-21 at 10 57 30 PM
WhatsApp Image 2020-10-21 at 10 57 30 PM(1)

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by VarunSAthreya — CHANGES_REQUESTED** [review]
There are a few minor changes:
1. Change the modal file name from `constraints.dart` to `members.dart`
2. Change the class name `MEMBERS` to `Members`

**Comment by singhtaran1005** [comment]
ok doing it

**Comment by singhtaran1005** [comment]
changes made!

**Review by VarunSAthreya — APPROVED** [review]
Congratulations on the successful merge!
The next set of issues would be out soon.

**Pull request merged**
