### PR TITLE
added social media icons with respective links

### LINKED ISSUE #9: GOSA8 - Social Media Links
#### Description
Add social media icons and their respective website. Use package 'url_launcher' to complete the task.

### PR DESCRIPTION
**Pull request by singhtaran1005**

### CODE REVIEW

**Review by VarunSAthreya — CHANGES_REQUESTED** [review]
Please send a PR to `Android-Development:development` branch.

**Comment by singhtaran1005** [comment]
sir sent a pr to development branch so should i delete this pr?

**Comment by VarunAthreya** [comment]
No just edit the branch.
Delete the new one.

**Comment by singhtaran1005** [comment]
actually i sent another pr so ? what to do

**Comment by singhtaran1005** [comment]
ok

**Comment by VarunAthreya** [comment]
I have done the changes please do it from next time.

**Comment by singhtaran1005** [comment]
ok sure i will remember thank you

**Review by VarunSAthreya — CHANGES_REQUESTED** [review]
Few changes after that pr will be merged. 
1. Change the folder name `pages` to `screens`.
2. Change the class name from `Developers` to `SocialMediaLinks`

**Comment by singhtaran1005** [comment]
okay doing it right now

**Comment by singhtaran1005** [comment]
sir just wanted to know if i should send new pr because it is not possible to change name of folder but i have changed the class name.

**Comment by singhtaran1005** [comment]
changes made!

**Comment by VarunAthreya** [comment]
Congratulations on the successful PR!
The next set of issues would be out soon.

**Pull request merged**
