### PR TITLE
Added the Embedded Map component at bottom of the Contact US screen

### LINKED ISSUE #97: GOSA36 - Add Embedded Map to Contact US screen
Add the Embedded Map component at bottom of the Contact US screen

### PR DESCRIPTION
**Pull request by singhtaran1005**
GOSA36
ISSUE #97 

#### Describe the changes you've made
Added the Embedded Map component at bottom of the Contact US screen.
#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by VarunSAthreya — CHANGES_REQUESTED** [review]
Instead of writing the same code, call the stateless widget instead of it.

**Comment by singhtaran1005** [comment]
ok

**Comment by singhtaran1005** [comment]
changes done

**Review by VarunSAthreya — APPROVED** [review]
Congratulations on the successful merge!
The results will be out soon!!!

**Pull request merged**
