### PR TITLE
Completed #59

### LINKED ISSUE #59: GOSA22 - Add Home Page
Add home page which contains UI for announcements and add the app drawer to all other screens and add `routeName` of the home screen to the app drawer.

### PR DESCRIPTION
**Pull request by rithik-dev**
- added drawer to all screens
- added announcements ui on homepage

#### Issue Number
ISSUE #59 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
added a new model announcement and a card to display them. Added homepage with some mock announcements.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [X] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.
- [X] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by VarunSAthreya — CHANGES_REQUESTED** [review]
On the login and signup screen after successful login/signup it navigates to `upcoming_evets_screen` change that to the home screen.

**Review by VarunSAthreya — CHANGES_REQUESTED** [review]
Only one change:
Add app drawer in  About Us screen

**Comment by rithik-dev** [comment]
It is already there I guess.

**Comment by rithik-dev** [comment]
Ohh .. so there is no app bar so it does not show the button. I'll add it

**Comment by VarunAthreya** [comment]
Yaa.

**Review by VarunSAthreya — APPROVED** [review]
Congratulations on the successful merge!
The next set of issues would be out soon.

**Pull request merged**
