### PR TITLE
Shruti j 01/GOSA2 UI for login with email and password

### LINKED ISSUE #3: GOSA2 - UI for login with email and password
#### Description
GeeksforGeeks Andriod App login the user with email and password. Create text fields to take email and password and authenticate the user using firebase.

### PR DESCRIPTION
**Pull request by ShrutiJ-01**
ISSUE#3
GOSA2 - UI for login with email and password #3 

Added UI for login with email and password. Created an images directory and added a graphic design that is supposed to be used in the UI. The UI has Email and password validation. If the data entered is valid, UI will authenticate and navigate to next page after the login button is pressed.If data is not valid UI will tell the user to correct the entered information.
#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
UI
ss4

validation screenshots
ss2
ss6
ss5
ss3

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?
In main.dart ,comment out preexisting code and paste this:
void main() => runApp(MyApp());
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home:LoginScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}
then run on the android emulator.

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by VarunSAthreya — CHANGES_REQUESTED** [review]
There is only one change:
Delete unwanted files/folders from root
1. build.gradle
2.  gradlew
3. gradlew.bat
4. local.propertier
5. .gradle
6. gradle/wrapper

**Comment by ShrutiJ-01** [comment]
okay, sir. Working on it!
I have some doubts regarding the changes.
1)I found two files named "build.gradle", they have the paths:
android/build.gradle
android/app/build.gradle 
Should I delete both of them?
2)I couldn't find a file named "local.propertier". 
I found one named "local.properties" instead. Should I delete the "local.properties" file now?

**Comment by VarunAthreya** [comment]
The changes are done! 
I'll merge now!

**Comment by ShrutiJ-01** [comment]
okay!

**Review by VarunSAthreya — APPROVED** [review]
Congratulations on the successful merge!
The next set of issues would be out soon.

**Pull request merged**
