### PR TITLE
Added new mission vision section---(Previous one had a issue)

### LINKED ISSUE #5: GOSA4 - UI for Mission and Vision section
#### Description
Geeksforgeeks student chapter Mission and Vision section.

You can use lorem placeholder text for content.

### PR DESCRIPTION
**Pull request by gharshg29**
#### Issue Number
ISSUE #5 

#### Describe the changes you've made
Added a splash screen along with 2 pages for the vision and mission section.

#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)

WhatsApp Image 2020-10-22 at 11 35 11 AM
WhatsApp Image 2020-10-22 at 11 35 11 AM (1)
WhatsApp Image 2020-10-22 at 11 35 11 AM (2)

#### Test plan (OPTIONAL)
NA

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by VarunSAthreya — CHANGES_REQUESTED** [review]
There are a few changes:
1. gitignore .vscode
2. Remove splash screen
3. Make Vision and Mission on the same screen

**Review by gharshg29 — COMMENTED** [review]
Changed to one page and removed the splash screen.

**Comment by geekyaditya100** [comment]
@gharshg29 resolve conflicts

**Review by gharshg29 — COMMENTED** [review]
Added main.dart

**Review by gharshg29 — COMMENTED** [review]
Changed class name and added screen folder

**Pull request merged**
