### PR TITLE
UI for Registration with email and with google auth

### LINKED ISSUE #2: GOSA1 - UI for Registration with email and with google auth
#### Description
GeeksforGeeks Andriod App registration with the help of email and other credentials or with help of google authentication. Create text fields to take relevant user data and create a user in user_data field in firebase. And also create a button to activate google authentication.

### PR DESCRIPTION
**Pull request by singhtaran1005**
GOSA1
ISSUE #2 

#### Describe the changes you've made
As told I had made UI for sign up page along with button for google sign in.I have made respective fields of name , email and password for registration and for now i had just pushed the google sign in button below to the sign up button which can be changed accordingly.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Screenshots added - 
WhatsApp Image 2020-10-23 at 12 54 14 AM

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by VarunSAthreya — CHANGES_REQUESTED** [review]
Few changes:
1. Add validation for an email address. (Hint: Check Regex for email validation)
2. Add validation for password i.e min length must be 8, must have 1 uppercase, 1 lower case, 1 digit, and 1 special character inside the password

**Comment by singhtaran1005** [comment]
ok doing!

**Comment by singhtaran1005** [comment]
changes done!

**Comment by singhtaran1005** [comment]
i have updated changes

**Review by VarunSAthreya — APPROVED** [review]
Congratulations on the successful merge!
The next set of issues would be out soon.

**Pull request merged**
