### PR TITLE
linked contact form to firebase

### LINKED ISSUE #47: GOSA18 - Connect Contact US form to firebase
Connect Contact US form to firebase with all given details

### PR DESCRIPTION
**Pull request by RakeshSeervi**
#### Issue Number
ISSUE #47 
GOSA18

#### Describe the changes you've made
Linked contact form to firebase; The pushing of data to firebase is being handled by a function defined in firebase_storage_service.dart file. Have used fluttertoast package to show toast messages.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
In main.dart, line 40, replace LoginScreen() with ContactUs()

#### Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/GameofSource-GFG/Web-Development/blob/main/CONTRIBUTING.md)** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by VarunSAthreya — CHANGES_REQUESTED** [review]
The package `fluttertoast` is already present to please remove duplicate one

**Comment by RakeshSeervi** [comment]
Made changes and resolved conflicts too. Just wanted to know if we are allowed to resolve merge conflicts ourselves?

**Comment by VarunAthreya** [comment]
If you are able to resolve then you can!

**Review by VarunSAthreya — APPROVED** [review]
Congratulations on the successful merge!
The next set of issues would be out soon.

**Pull request merged**
